excluded:
  - Pods
disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - notification_center_detachment
  - todo
  - type_body_length
  - vertical_whitespace
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - file_header
  - first_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - number_separator
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - redundant_nil_coalescing
  - trailing_closure
  - vertical_parameter_alignment_on_call

number_separator:
  minimum_length: 5
